### ISSUE TITLE
Not working. Cannot import Solver.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrisidefix/pyfem#1]
```
What steps will reproduce the problem?
1.Have downloaded the zip pacakage and run the install script. 
2.Have also installed the .exe file.
3.But when I try ti starrt PyFEM.py I got this error message

Command Line : StressWave_20x20.dat
Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "C:\Python27\pyfem-1.0\PyFEM.py", line 30, in <module>
    from pyfem.solvers.Solver   import Solver
ImportError: No module named So


What version of the product are you using? On what operating system?
Version 1.0 on Windows 7

Please provide any additional information below.


```

Original issue reported on code.google.com by `trof...@gmail.com` on 17 Sep 2014 at 7:35

**Comment by GoogleCodeExporter** [comment]
```
Can neither find no module called MaterialManager. It like a lot of modules is 
missing. I have bought the book and think it sad that this do not work:( Really 
like the book.
```

Original comment by `trof...@gmail.com` on 23 Sep 2014 at 9:56
